export type RootStackParamList = {
  Walkthrough: undefined;
  Start: undefined;
  Login: undefined;
  SignUp: undefined;
  Main: undefined;
  Notification: undefined;
  ChooseAddress: { type: 'pickup' | 'delivery'; onSelect?: (address: { address: string, latitude: number, longitude: number }) => void };
  DeliveryMiles: undefined;
  TransitAndReceiverDetails: { orderData?: { pickupLocation: { address: string, latitude: number, longitude: number }, deliveryLocation: { address: string, latitude: number, longitude: number } } };
  MyReviews: undefined;
  ChangePassword: undefined;
  Terms: undefined;
  Privacy: undefined;
  Support: undefined;
  Profile: undefined;
  EditProfile: undefined;
  WebViewScreen: { title: string; url: string };
  ContactUs: undefined;
  DeliveryDetails: { orderId: string };
  ItemDetails: { orderData: any };
  DeliverySelection: { orderData: any };
  PaymentOptions: { orderData: any };
  ForgotPassword: { type: 'email' | 'phone' };
  OTPVerification: { type: 'email' | 'phone'; value: string; userData?: any; fromScreen?: string };
  NewPassword: { userId: string };
  DeliveryConfirmation: { orderData: any; fromHistory?: boolean };
  ReceivingOrderHistory?: { isFromSettings?: boolean; title?: string };
  Chat: { orderId: string };
  OrderTrack: undefined;
};