
export const LocalStorage = {
  onboarding: 'onboarding',
  isLoggedIn: 'isLoggedIn',
  token: 'token',
  user: 'user',
  isVerified: 'isVerified',
  isOnboarded: 'isOnboarded',
  splashOnboarding: 'splashOnboarding',
  email: 'email',
  fakePassword: 'fakePassword',
  userDetails: 'userDetails',
  cameraPermission: 'cameraPermission',
  storagePermission: 'storagePermission',
  audioPermission: 'audioPermission',
  createTribePayment: 'createTribePayment1',
  createTribeSubmission: 'createTribeSubmission',
  createTribeData: 'createTribeData',
  firstTribeCreated: 'firstTribeCreated',
  loggedIn: 'loggedIn',
  tribeCode: 'tribeCode',
};
